name: Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Library Version (SemVer: https://semver.org)'
        required: true
jobs:
  deploy:
    name: "NuGet Deployment"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build DiscordMessenger/DiscordMessenger.csproj --configuration Release --no-restore
    - name: Push to NuGet
      run: dotnet nuget push /home/runner/work/DiscordMessenger/DiscordMessenger/DiscordMessenger/bin/Release/DiscordMessenger.${{ github.event.inputs.version }}.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json
